const data = [
	{ id: 1, question: "Where is Nigeria located", options: [{ a: "Africa", b: "America", c: "Asia" }], answer: "Africa", touch: false, selected: "" },
	{ id: 2, question: "Where is Naka located", options: [{ a: "Lagos", b: "Benue", c: "Kogi" }], answer: "Benue", touch: false, selected: "" },
	{ id: 3, question: "Where is Texas located", options: [{ a: "Africa", b: "America", c: "Asia" }], answer: "America", touch: false, selected: "" },
	{ id: 4, question: "Where is lekki located", options: [{ a: "Lagos", b: "Benue", c: "Kogi" }], answer: "Lagos", touch: false, selected: "" },
	{ id: 5, question: "Where is Imo located", options: [{ a: "Africa", b: "America", c: "Asia" }], answer: "Africa", touch: false, selected: "" },
	{ id: 6, question: "Where is Philipian located", options: [{ a: "Lagos", b: "Asia", c: "Kogi" }], answer: "Asia", touch: false, selected: "" },
	{ id: 7, question: "Where is Corea located", options: [{ a: "Africa", b: "America", c: "Asia" }], answer: "Africa", touch: false, selected: "" },
	{ id: 8, question: "Where is Naka located", options: [{ a: "Lagos", b: "Benue", c: "Kogi" }], answer: "Benue", touch: false, selected: "" },
	{ id: 9, question: "Where is Nigeria located", options: [{ a: "Africa", b: "America", c: "Asia" }], answer: "Africa", touch: false, selected: "" },
	{ id: 10, question: "Where is Naka located", options: [{ a: "Lagos", b: "Benue", c: "Kogi" }], answer: "Benue", touch: false, selected: "" },
	{ id: 11, question: "Where is Japan located", options: [{ a: "Africa", b: "America", c: "Asia" }], answer: "Africa", touch: false, selected: "" },
	{ id: 12, question: "Where is Naka located", options: [{ a: "Lagos", b: "Benue", c: "Kogi" }], answer: "Benue", touch: false, selected: "" },
	{ id: 13, question: "Where is Nigeria located", options: [{ a: "Africa", b: "America", c: "Asia" }], answer: "Africa", touch: false, selected: "" },
	{ id: 14, question: "Where is Naka located", options: [{ a: "Lagos", b: "Benue", c: "Kogi" }], answer: "Benue", touch: false, selected: "" },
	{ id: 15, question: "Where is Nigeria located", options: [{ a: "Africa", b: "America", c: "Asia" }], answer: "Africa", touch: false, selected: "" },
	{ id: 16, question: "Where is Makurdi located", options: [{ a: "Lagos", b: "Benue", c: "Kogi" }], answer: "Benue", touch: false, selected: "" },
	{ id: 17, question: "Where is Nigeria located", options: [{ a: "Africa", b: "America", c: "Asia" }], answer: "Africa", touch: false, selected: "" },
	{ id: 18, question: "Where is Makurdi located", options: [{ a: "Lagos", b: "Benue", c: "Kogi" }], answer: "Benue", touch: false, selected: "" },
	{ id: 19, question: "Where is Naka located", options: [{ a: "Lagos", b: "Benue", c: "Kogi" }], answer: "Benue", touch: false, selected: "" },
	{ id: 20, question: "Where is Nigeria located", options: [{ a: "Africa", b: "America", c: "Asia" }], answer: "Africa", touch: false, selected: "" },
	{ id: 21, question: "Where is Naka located", options: [{ a: "Lagos", b: "Benue", c: "Kogi" }], answer: "Benue", touch: false, selected: "" },
	{ id: 22, question: "Where is Japan located", options: [{ a: "Africa", b: "America", c: "Asia" }], answer: "Africa", touch: false, selected: "" },
	{ id: 23, question: "Where is Naka located", options: [{ a: "Lagos", b: "Benue", c: "Kogi" }], answer: "Benue", touch: false, selected: "" },
	{ id: 24, question: "Where is Nigeria located", options: [{ a: "Africa", b: "America", c: "Asia" }], answer: "Africa", touch: false, selected: "" },
	{ id: 25, question: "Where is Naka located", options: [{ a: "Lagos", b: "Benue", c: "Kogi" }], answer: "Benue", touch: false, selected: "" },
	{ id: 26, question: "Where is Nigeria located", options: [{ a: "Africa", b: "America", c: "Asia" }], answer: "Africa", touch: false, selected: "" },
	{ id: 27, question: "Where is Makurdi located", options: [{ a: "Lagos", b: "Benue", c: "Kogi" }], answer: "Benue", touch: false, selected: "" },
	{ id: 28, question: "Where is Nigeria located", options: [{ a: "Africa", b: "America", c: "Asia" }], answer: "Africa", touch: false, selected: "" },
	{ id: 29, question: "Where is Makurdi located", options: [{ a: "Lagos", b: "Benue", c: "Kogi" }], answer: "Benue", touch: false, selected: "" },
	{ id: 30, question: "what is Makurdi located", options: [{ a: "Lagos", b: "Benue", c: "Kogi" }], answer: "Benue", touch: false, selected: "" },
];

export default data;
